import "../styles/globals.scss";
import { ptSans, montserrat, lato } from "@/fonts/fonts";
// import styles from "@/app/page.module.scss";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <body className={ `${ ptSans.variable } ${ lato.variable } ${ montserrat.variable }` }>
    <main className="main">
      { children }
    </main>
    <div id="modal-root"/>
    </body>
    </html>
  );
}
